Add CI Workflow
blacksky-algorithms/rsky pull request #2
Opened 2024-06-23 17:30 UTC by DrewMcArthur

- adds `rust-toolchain`, which specifies a specific nightly rust version (2024-06-23)
- adds `.github/workflows/rust.yml`, which does a `cargo check, build, test` in that order
- fixes a couple of build errors

2024-06-23 17:35 UTC, DrewMcArthur commented on .github/workflows/rust.yml
> +  #     run: cargo fmt -- --check
this fails, let me know if you would rather just delete it for now

2024-06-23 17:35 UTC, DrewMcArthur commented on rsky-firehose/src/main.rs
> +                                            create.prev = commit.prev.clone();
could probably move this up into the initialization above; I took out the `if` since the variable we're setting is an `Option` too

2024-06-24 01:31 UTC, rudyfraser commented on rsky-lexicon/src/com/atproto/sync.rs
When I try this locally I get `the trait bound 'CidGeneric<64>: serde::Deserialize<'_>' is not satisfied [E0277]`. I prefer to use the Cid type for cid values whenever possible but found that I get this issue with serde. Do you see the same on your end?

2024-06-24 01:35 UTC, rudyfraser requested changes
Most of this looks good to me! See my comment about `rsky-lexicon/src/com/atproto/sync.rs` which is the sole concern I have as I get errors for that change on my side.

2024-06-24 02:47 UTC, DrewMcArthur commented on rsky-lexicon/src/com/atproto/sync.rs
i do not, I made this change because I was getting the following error from `cargo check`:

```
error[E0308]: mismatched types
   --> rsky-firehose/src/main.rs:136:84
    |
136 | ...                   let record_reader = Cursor::new(car_blocks.get(&cid).unwrap());
    |                                                                  --- ^^^^ expected `&Cid<64>`, found `&String`
    |                                                                  |
    |                                                                  arguments to this method are incorrect
    |
    = note: expected reference `&cid::cid::Cid<64>`
               found reference `&std::string::String`
```

note, my cargo/rustc version is: `cargo 1.81.0-nightly (bc89bffa5 2024-06-22)`.  I rolled back this file with `git checkout origin/pds -- rsky-lexicon/src/com/atproto/sync.rs`.

2024-06-24 03:33 UTC, DrewMcArthur commented on rsky-lexicon/src/com/atproto/sync.rs
ah! I was able to get your error by bumping up a few versions (`cid` to `0.11.1` and `serde_ipld_dagcbor` to `0.6.1`).  hm.

2024-06-24 05:35 UTC, rudyfraser commented on rsky-lexicon/src/com/atproto/sync.rs
Sounds good! I also know that rsky-firehose and rsky-feedgen use a different Cid library than rsky-pds and rsky-lexicon.
The PDS uses the cid from libipld which I think is the right one to use.
I'll open an issue for fixing the firehose code and using libipld if you don't mind holding off on making changes to rsky-firehose and rsky-feedgen for now.

2024-06-24 12:05 UTC, closed without merging

2024-06-24 12:06 UTC, DrewMcArthur commented
closed in favor of #10